### ISSUE TITLE
PHP notices: Undefined index SERVER_PORT and SERVER_NAME

### ISSUE THREAD

**Issue by rumspeed** [rumspeed/simple-side-tab#10]
This issue was reported in this WordPress repo support thread:
https://wordpress.org/support/topic/php-notices-undefined-index-server_port-and-server_name

Try to replicate the issue and apply a fix accordingly. 

I think I can check isset() in the code on those lines to check the variables. They should be there but maybe there are cases where they are not available.

**Comment by rebdev** [comment]
Hey Scot, thanks for responding. Looking at it again, I've realised it's only going to be a WP-CLI problem, so you may or may not want to do anything about it: sorry to have jumped the gun and gotten you concerned. It's because it's command line PHP I'm using (WP-CLI being a command line interface to WordPress); the $_SERVER array isn't getting set because there is no web server invoking it. Hence the PHP notices on the command line as I attempt to perform updates using WP-CLI. I've found a few other reports of people using WP-CLI and having similar issues where the $_SERVER array is referenced, eg https://github.com/wp-cli/wp-cli/issues/1734 and https://github.com/wp-cli/wp-cli/issues/785#issuecomment-138040347

You're right, checking isset() would solve them. When I wrapped everything in the rum_get_full_url() function with  'if(isset($_SERVER["SERVER_NAME"]))', the notices ceased.

At line 100:
// get the complete url for the current page
function rum_get_full_url()
{
	if(isset($_SERVER["SERVER_NAME"])) {
		$s 			= empty($_SERVER["HTTPS"]) ? '' : ($_SERVER["HTTPS"] == "on") ? "s" : "";
		$sp 		= strtolower($_SERVER["SERVER_PROTOCOL"]);
		$protocol 	= substr($sp, 0, strpos($sp, "/")) . $s;
		$port 		= ($_SERVER["SERVER_PORT"] == "80") ? "" : (":".$_SERVER["SERVER_PORT"]);
		return $protocol . "://" . $_SERVER['SERVER_NAME'] . $port . $_SERVER['REQUEST_URI'];
	}
}

**Comment by rumspeed** [comment]
Thank you for the great follow up, Becc. I have implemented the change and it will be available on the next release. I'm planning on having it completed within the week. It's currently fixed on the "release-v1.2.0" branch but not rolled into master and tagged just yet.
